sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.npm

env:
  global:
    - NODE_VERSION="10.16.0"
    # AWS_ACCESS_KEY_ID
    - secure: "CplvtL9y2xUq4kqruHoHosfWlRoXSwAHvF5GFMf7y9xm+Th37nO4iGGnuGy0gpVuvqcvFZ8MOOdWLq2F5ipNKAvzrkOzgl8kcNU17Jq4Si9xyZKkmoPTE918ANuqTxZHJeRN17O00sK/x+/9CKOgsoVH7Fp1LZV4R+BlghfQ59HMxRkYtC/eIbHg/Oo4XpglhbTI0uTKjARawTmZZxpz88KcbhMpvA/SyubzwV4f/VPtxOd4RO36q5CfjzbZvV/fGLcwYfNy6jWjrKdVty3L97ZRRETMABgoZia33ITHptGnXa+J0V/OPrvwGrQOWfTme2dW+a0bio1k/exrfRNauVTkMhTN1uYaLYuB1eB4H6HChVaz6LtCiqbX7XHoiiDJiK402doq8bJ73JAouzvxOsNPNrGzen3tn58wSqEJj7/cONgH8iFfM6unkkpibQeYJFS3Z+XWx7In37+h9YLO+yrHtQV9HNed2u06O06k5F6CFkRMfV5PmoZgA/Bli2w230S7J4ZZEua5HOrpLgd8DzP+CXenjobvHTFkfQSF4T6ueN6pYyYE6RaeS+yZ33TIVVH6xG9VIqnUX3ubbDC+kehFF/+Zk3j77CWCFEdHsErNx8qstyPSzE3R4IUeg87fE0bmcvp3Lc1yekx9o1c3QbZsXJypVSC88ZGuMDlYdZM="
    # AWS_SECRET_ACCESS_KEY
    - secure: "FGlqNW6hqKHid3vLTfpgKYEKDTohM0dCzC0Us3mf6TV+CJEoc28xMYIJM+cMrlmBEl58L3ZOa/9NOkNW2QTcsfxbuy2KL7rW9HJww8AiwT3lAu0uxWltDCd3pfXmxdbYd+eDUa+GcFEgo8n7dqsPwjB7tQAdOkUidWxIM0RSVpan2uOufU1PSwTlFip5Jut1GQT0pD7LS3FzMfU+LjmteADv2raQ+TpV6AymV7LvGKbeveWgE4pEOBGDmU0/JUZEnZhsp3pEBOHxcr128RL8DkW2pYtY5B2xibY9De9cwk1GE6zmcS9ecsgYwiAlQ2rZct2gc4XnZdqJIxS+i8EWaq8sFJLPP7v+PGv6LBf9dCNoAMqeB6/GUGAhbJTBMHTjJUoAb2CDtRMaltLVcqkEOoRcLYgShqjEjqzX6326eNE6tp1oJnwg4bOLZ8wP8nxVfveGTagpR4mccRzn8MgY0l3MlDMl7EhKnyVr/IHubeSGfynPYvDIM8QwAvI8UKmxxSIULTSp1EgZy/aADEd+L6TV/Bg7K8KrbNdLyfjND4cET0hlcJddKm+4v5M2daNidB5n0zpKsppaiE2w8T06hIZR6d5OyQV/KypfhE2rpfTf4DVXN6E8lGy3Igh0cZTC45vrz4vqBrlM0qJBaoh7OG1RPTQWgh1a4sH9jqMXoSo="

before_install:
  - nvm install $NODE_VERSION

install:
  - git clone --recurse-submodules --depth 1 https://github.com/Opetushallitus/eperusteet-amosaa-ui.git
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="eperusteet-amosaa"

script:
  # Rakennetaan uusi UI
  - export AMOSAA_SERVICE_DIR=$TRAVIS_BUILD_DIR/eperusteet-amosaa-service
  - cd eperusteet-amosaa-ui
  - yarn install --silent
  - cd eperusteet-frontend-utils/vue
  - yarn install --silent
  - yarn gen:api
  - rm -rf node_modules
  - cd ../..
  - git rev-parse HEAD
  - yarn run build
  - cd ..

  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv ${ARTIFACT_NAME}-service/target/${ARTIFACT_NAME}-service.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-service.war
  - mv ${ARTIFACT_NAME}-app/target/${ARTIFACT_NAME}-app.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}-app.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
  - cp -vr src/main/resources/tomcat $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-tomcat8-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh ${ARTIFACT_NAME}

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
  on:
    all_branches: true
