CREATE INDEX opetussuunnitelma_nimi_index on opetussuunnitelma(nimi_id);
CREATE INDEX opetussuunnitelma_tila_index on opetussuunnitelma(tila);
CREATE INDEX opetussuunnitelma_tyyppi_index on opetussuunnitelma(tyyppi);
CREATE INDEX opetussuunnitelma_koulutustyyppi_index on opetussuunnitelma(koulutustyyppi);
CREATE INDEX opetussuunnitelma_jotpatyyppi_index on opetussuunnitelma(jotpatyyppi);